package com.joneshshrestha.rentalapp;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class Report {
    // method that prints reportable to console
    public static void printToConsole(Reportable reportable) {
        System.out.println(reportable.generateReport());
    }
    // method that creates a csv file using the data generated by the Reportable interface
    public static void persistToCSV(Reportable reportable, String fileName) {
        // try closes the writer automatically after writing
        // BufferedWriter buffers data to be written to memory first and writes them at once which improves performance
        // FileWriter opens the fileName for writing which overwrites existing content
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            // writer.write() writes the provided string to the file
            writer.write(reportable.generateReport());
            // IO error handling block that catches any exception and displays in the console
        } catch (IOException e) {
            System.out.println("Error writing to CSV file: " + e.getMessage());
        }
    }
}
